// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
declare const styles: {
	readonly wrapper: string;
	readonly foo: string;
	readonly bar: string;
};

export default styles;

// # sourceMappingURL=styles.module.scss.d.ts.map
